# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - EC-WIN-24-NET-Forge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x' # Consider using a specific LTS version like '8.0.x' unless you require .NET 9 features

      - name: Build with dotnet
        run: dotnet build Presentation.sln --configuration Release

      - name: dotnet publish
        # Replace 'Path/To/YourActualWebAppProject.csproj' with the relative path to your main web application project file
        # For example, if your web app project is in a folder 'Forge.WebApp' and named 'Forge.WebApp.csproj',
        # use 'Forge.WebApp/Forge.WebApp.csproj'
        run: dotnet publish Forge.csproj -c Release -o ${{ github.workspace }}/myappoutput

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myappoutput

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production' # Ensure 'Production' environment is configured in your repo settings
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          # By default, this downloads to GITHUB_WORKSPACE
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7A6F183D861943739B96F37A463D2D31 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_20162C0A5BFB4AC5BC835413DC094484 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C9FC5F1E543047659BEE1FE4E6C09362 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EC-WIN-24-NET-Forge'
          slot-name: 'Production'
          package: . # This should be correct if myappoutput contained the app files directly
